# Generated by Django 6.0.5 on 2026-05-30 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anagrafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crp_nome', models.CharField(blank=True, max_length=120, verbose_name='nome CRP')),
                ('crp_cognome', models.CharField(blank=True, max_length=120, verbose_name='cognome CRP')),
                ('crp_email', models.EmailField(blank=True, max_length=254, verbose_name='email CRP')),
                ('crp_cell', models.CharField(blank=True, max_length=30, verbose_name='cellulare CRP')),
                ('email_contatto', models.EmailField(blank=True, max_length=254, verbose_name='email contatto')),
                ('cell_contatto', models.CharField(blank=True, max_length=30, verbose_name='cellulare contatto')),
                ('specialita', models.CharField(blank=True, max_length=120, verbose_name='specialità di squadriglia')),
                ('partecipa_evento', models.BooleanField(default=True, verbose_name="partecipa all'evento GV")),
                ('desc_prima_impresa', models.TextField(blank=True, verbose_name='descrizione 1ª impresa (da import)')),
                ('desc_seconda_impresa', models.TextField(blank=True, verbose_name='descrizione 2ª impresa (da import)')),
                ('tecniche', models.TextField(blank=True, verbose_name='tecniche da acquisire (da import)')),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'anagrafica',
                'verbose_name_plural': 'anagrafiche',
            },
        ),
        migrations.CreateModel(
            name='EsitoSpecialita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='specialità/brevetto')),
                ('stato', models.CharField(choices=[('conquistata', 'Conquistata'), ('non_conquistata', 'Non conquistata'), ('in_cammino', 'In cammino')], default='in_cammino', max_length=20)),
            ],
            options={
                'verbose_name': 'esito specialità',
                'verbose_name_plural': 'esiti specialità',
            },
        ),
        migrations.CreateModel(
            name='Impresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, '1ª impresa'), (2, '2ª impresa')])),
                ('titolo', models.CharField(blank=True, max_length=200)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('perche', models.TextField(blank=True, verbose_name='perché')),
                ('come', models.TextField(blank=True)),
                ('cosa', models.TextField(blank=True)),
                ('link_esterno', models.URLField(blank=True, verbose_name='link esterno (video/materiale)')),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'impresa',
                'verbose_name_plural': 'imprese',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='MembroSq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cognome', models.CharField(max_length=60)),
                ('ruolo', models.CharField(blank=True, max_length=60, verbose_name='ruolo in squadriglia')),
                ('sentiero', models.CharField(choices=[('prima_tappa', 'Prima tappa'), ('seconda_tappa', 'Seconda tappa'), ('terza_tappa', 'Terza tappa'), ('quarta_tappa', 'Quarta tappa'), ('non_specificato', 'Non specificato')], default='non_specificato', max_length=20)),
            ],
            options={
                'verbose_name': 'membro squadriglia',
                'verbose_name_plural': 'membri squadriglia',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Missione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, max_length=200)),
                ('data', models.DateField(blank=True, null=True)),
                ('descrizione_svolgimento', models.TextField(blank=True)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'missione',
                'verbose_name_plural': 'missioni',
            },
        ),
        migrations.CreateModel(
            name='PostoAzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': "posto d'azione",
                'verbose_name_plural': "posti d'azione",
            },
        ),
        migrations.CreateModel(
            name='PostoAzioneMissione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': "posto d'azione (missione)",
                'verbose_name_plural': "posti d'azione (missione)",
            },
        ),
        migrations.CreateModel(
            name='Presentazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosa_sappiamo_fare', models.TextField(blank=True, verbose_name='cosa sappiamo fare')),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'presentazione squadriglia',
                'verbose_name_plural': 'presentazioni squadriglia',
            },
        ),
        migrations.CreateModel(
            name='RelazioneFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintesi_impresa_1', models.TextField(blank=True, verbose_name='sintesi 1ª impresa')),
                ('sintesi_impresa_2', models.TextField(blank=True, verbose_name='sintesi 2ª impresa')),
                ('sintesi_missione', models.TextField(blank=True, verbose_name='sintesi missione')),
                ('considerazioni', models.TextField(blank=True, verbose_name='considerazioni finali')),
                ('specialita_conquistata', models.BooleanField(blank=True, null=True, verbose_name='specialità conquistata')),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'relazione finale',
                'verbose_name_plural': 'relazioni finali',
            },
        ),
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('impresa_1', '1ª impresa'), ('impresa_2', '2ª impresa'), ('missione', 'Missione')], max_length=20)),
                ('tipo', models.CharField(default='foto', max_length=10)),
                ('drive_file_id', models.CharField(blank=True, max_length=200)),
                ('nome', models.CharField(max_length=255)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('dimensione', models.PositiveIntegerField(default=0, help_text='bytes')),
                ('stato_sync', models.CharField(choices=[('locale', 'Solo locale'), ('in_coda', "In coda per l'upload"), ('caricato', 'Caricato su Drive')], default='locale', max_length=10)),
                ('creato_at', models.DateTimeField(auto_now_add=True)),
                ('caricato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allegati_caricati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'allegato',
                'verbose_name_plural': 'allegati',
                'ordering': ['modulo', 'creato_at'],
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuovo', 'Nuovo'), ('rinnovo', 'Rinnovo')], default='nuovo', max_length=10)),
                ('stato', models.CharField(choices=[('in_compilazione', 'In compilazione'), ('inviato', 'Inviato'), ('in_valutazione', 'In valutazione'), ('in_revisione', 'In revisione'), ('approvato', 'Approvato'), ('non_approvato', 'Non approvato'), ('maggiori_info', 'Maggiori informazioni richieste')], db_index=True, default='in_compilazione', max_length=20)),
                ('scadenza_riferimento', models.CharField(choices=[('prima', 'Prima scadenza (evento)'), ('seconda', 'Seconda scadenza (assemblea)')], default='prima', max_length=10)),
                ('pubblicato_at', models.DateTimeField(blank=True, null=True)),
                ('csq_completato_at', models.DateTimeField(blank=True, null=True)),
                ('inviato_at', models.DateTimeField(blank=True, null=True)),
                ('creato_at', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
                ('crp', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'capo'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diari_crp', to='org.socio', verbose_name='capo reparto')),
                ('csq', models.ForeignKey(blank=True, limit_choices_to={'categoria': 'ragazzo'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diari_csq', to='org.socio', verbose_name='capo squadriglia')),
            ],
            options={
                'verbose_name': 'diario',
                'verbose_name_plural': 'diari',
                'ordering': ['squadriglia__reparto__gruppo__zona__nome', 'squadriglia__nome'],
            },
        ),
    ]
