# Generated by Django 6.0.5 on 2026-05-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0001_initial'),
        ('editions', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='edizione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diari', to='editions.edizione'),
        ),
        migrations.AddField(
            model_name='diario',
            name='squadriglia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diari', to='org.squadriglia'),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='diario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anagrafica', to='diaries.diario'),
        ),
        migrations.AddField(
            model_name='allegato',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allegati', to='diaries.diario'),
        ),
        migrations.AddField(
            model_name='impresa',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imprese', to='diaries.diario'),
        ),
        migrations.AddField(
            model_name='esitospecialita',
            name='impresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esiti_specialita', to='diaries.impresa'),
        ),
        migrations.AddField(
            model_name='missione',
            name='diario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='missione', to='diaries.diario'),
        ),
        migrations.AddField(
            model_name='postoazione',
            name='impresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posti_azione', to='diaries.impresa'),
        ),
        migrations.AddField(
            model_name='postoazionemissione',
            name='missione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posti_azione', to='diaries.missione'),
        ),
        migrations.AddField(
            model_name='presentazione',
            name='diario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentazione', to='diaries.diario'),
        ),
        migrations.AddField(
            model_name='membrosq',
            name='presentazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membri', to='diaries.presentazione'),
        ),
        migrations.AddField(
            model_name='relazionefinale',
            name='diario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relazione_finale', to='diaries.diario'),
        ),
        migrations.AlterUniqueTogether(
            name='diario',
            unique_together={('edizione', 'squadriglia')},
        ),
        migrations.AlterUniqueTogether(
            name='impresa',
            unique_together={('diario', 'numero')},
        ),
    ]
