# Generated by Django 6.0.5 on 2026-06-01 06:06

import apps.diaries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegato',
            name='file',
            field=models.FileField(blank=True, help_text="Rimosso dopo l'upload su Drive", null=True, upload_to=apps.diaries.models._allegato_upload_to, verbose_name='file locale'),
        ),
    ]
