# Generated by Django 6.0.5 on 2026-06-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_allegato_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagrafica',
            name='cell_contatto',
        ),
        migrations.RemoveField(
            model_name='anagrafica',
            name='email_contatto',
        ),
        migrations.AddField(
            model_name='esitospecialita',
            name='tipo',
            field=models.CharField(choices=[('specialita', 'Specialità'), ('brevetto', 'Brevetto')], default='specialita', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='specialita',
            field=models.CharField(blank=True, choices=[('', '— Scegli —'), ('Alpinismo', 'Alpinismo'), ('Artigianato', 'Artigianato'), ('Campismo', 'Campismo'), ('Civitas', 'Civitas'), ('Esplorazione', 'Esplorazione'), ('Espressione', 'Espressione'), ('Giornalismo', 'Giornalismo'), ('Internazionale', 'Internazionale'), ('Natura', 'Natura'), ('Nautica', 'Nautica'), ('Olimpia', 'Olimpia'), ('Pronto Intervento', 'Pronto Intervento')], max_length=120, verbose_name='specialità di squadriglia'),
        ),
        migrations.AlterField(
            model_name='esitospecialita',
            name='nome',
            field=models.CharField(max_length=120, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='membrosq',
            name='ruolo',
            field=models.CharField(blank=True, choices=[('csq', 'Capo Squadriglia'), ('vcsq', 'Vice Capo Squadriglia'), ('squadrigliere', 'Squadrigliere'), ('altro', 'Tutti gli altri')], max_length=20, verbose_name='ruolo in squadriglia'),
        ),
        migrations.AlterField(
            model_name='membrosq',
            name='sentiero',
            field=models.CharField(choices=[('scoperta', 'Scoperta'), ('competenza', 'Competenza'), ('responsabilita', 'Responsabilità'), ('non_specificato', 'Non specificato')], default='non_specificato', max_length=20),
        ),
    ]
