# Generated by Django 6.0.5 on 2026-06-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_specialita_brevetti_ruolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='stato',
            field=models.CharField(choices=[('in_compilazione', 'In compilazione'), ('relazione_finale', 'Relazione finale'), ('inviato', 'Inviato'), ('in_valutazione', 'In valutazione'), ('in_revisione', 'In revisione'), ('approvato', 'Approvato'), ('non_approvato', 'Non approvato'), ('maggiori_info', 'Maggiori informazioni richieste')], db_index=True, default='in_compilazione', max_length=20),
        ),
    ]
