# Generated by Django 6.0.5 on 2026-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_stato_non_iniziato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membrosq',
            options={'ordering': ['nome'], 'verbose_name': 'membro squadriglia', 'verbose_name_plural': 'membri squadriglia'},
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='csq_cell',
            field=models.CharField(blank=True, max_length=30, verbose_name='cellulare Capo Squadriglia'),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='csq_cognome',
            field=models.CharField(blank=True, max_length=120, verbose_name='cognome Capo Squadriglia'),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='csq_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email Capo Squadriglia'),
        ),
        migrations.AddField(
            model_name='anagrafica',
            name='csq_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome Capo Squadriglia'),
        ),
        migrations.AddField(
            model_name='esitospecialita',
            name='chi',
            field=models.CharField(blank=True, max_length=120, verbose_name='chi'),
        ),
        migrations.AddField(
            model_name='postoazione',
            name='chi',
            field=models.CharField(blank=True, max_length=200, verbose_name='chi'),
        ),
        migrations.AddField(
            model_name='postoazione',
            name='cosa',
            field=models.CharField(blank=True, max_length=300, verbose_name='cosa'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='crp_cell',
            field=models.CharField(blank=True, max_length=30, verbose_name='cellulare Capo Reparto'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='crp_cognome',
            field=models.CharField(blank=True, max_length=120, verbose_name='cognome Capo Reparto'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='crp_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email Capo Reparto'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='crp_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome Capo Reparto'),
        ),
        migrations.AlterField(
            model_name='anagrafica',
            name='partecipa_evento',
            field=models.BooleanField(default=True, verbose_name="partecipa all'evento Guidoncini Verdi"),
        ),
        migrations.AlterField(
            model_name='membrosq',
            name='cognome',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='membrosq',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='postoazione',
            name='descrizione',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
