# Generated by Django 6.0.5 on 2026-06-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0009_data_postoazione_split_jotform'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagrafica',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresa',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missione',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presentazione',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
