# Generated by Django 6.0.5 on 2026-05-30 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('editions', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='edizione',
            field=models.ForeignKey(blank=True, help_text='Valorizzato solo per i ruoli contestuali CRP/CSQ.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomine', to='editions.edizione'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='nominato_da',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomine_effettuate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nomina',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomine', to='org.socio'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='utente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomine', to=settings.AUTH_USER_MODEL),
        ),
    ]
