# Generated by Django 6.0.5 on 2026-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='attiva',
            field=models.BooleanField(default=True, help_text="False se revocata. Il record rimane per l'audit trail."),
        ),
        migrations.AddField(
            model_name='nomina',
            name='scadenza',
            field=models.DateField(blank=True, help_text='Scadenza opzionale (PGV, IABR, Segreteria). Null = nessuna scadenza.', null=True),
        ),
    ]
