# Generated by Django 6.0.5 on 2026-05-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0002_initial'),
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveCredenziali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'credenziali Drive',
                'verbose_name_plural': 'credenziali Drive',
            },
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=200, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('pdf', 'PDF diario'), ('excel', 'Excel esiti')], max_length=10)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('dimensione', models.PositiveIntegerField(default=0)),
                ('url_esterno', models.URLField(blank=True)),
                ('caricato_at', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_files', to='diaries.diario')),
                ('edizione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drive_files', to='editions.edizione')),
            ],
            options={
                'verbose_name': 'file Drive',
                'verbose_name_plural': 'file Drive',
                'ordering': ['-caricato_at'],
            },
        ),
    ]
