# Generated by Django 6.0.5 on 2026-05-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(default='diario', max_length=40, unique=True)),
                ('contenuto_html', models.TextField()),
                ('versione', models.PositiveIntegerField(default=1)),
                ('attivo', models.BooleanField(default=True)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
