# Generated by Django 6.0.5 on 2026-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTaskExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF diario'), ('excel', 'Excel edizione')], max_length=20)),
                ('stato', models.CharField(choices=[('ok', 'Completato'), ('errore', 'Errore')], max_length=20)),
                ('messaggio', models.TextField(blank=True)),
                ('traceback_testo', models.TextField(blank=True, verbose_name='traceback')),
                ('diario_pk', models.IntegerField(blank=True, null=True)),
                ('diario_str', models.CharField(blank=True, max_length=200)),
                ('utente_pk', models.IntegerField(blank=True, null=True)),
                ('utente_str', models.CharField(blank=True, max_length=200)),
                ('creato_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log export',
                'verbose_name_plural': 'Log export',
                'ordering': ['-creato_at'],
            },
        ),
    ]
