# Generated by Django 6.0.5 on 2026-06-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_logtaskexport'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtaskexport',
            name='edizione_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logtaskexport',
            name='edizione_str',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='logtaskexport',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF diario'), ('excel', 'Excel edizione'), ('pdf_massivo', 'PDF massivo edizione')], max_length=20),
        ),
    ]
