# Generated by Django 6.0.5 on 2026-05-30 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.PositiveIntegerField(unique=True, verbose_name='anno')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('aperta', 'Aperta'), ('in_valutazione', 'In valutazione'), ('chiusa', 'Chiusa')], default='bozza', max_length=20)),
                ('scadenza_evento', models.DateField(blank=True, null=True, verbose_name='prima scadenza (evento)')),
                ('scadenza_assemblea', models.DateField(blank=True, null=True, verbose_name='seconda scadenza (assemblea)')),
                ('data_evento', models.DateField(blank=True, null=True, verbose_name='data evento GV')),
                ('drive_folder_foto_id', models.CharField(blank=True, max_length=200, verbose_name='ID cartella Drive foto')),
                ('drive_folder_output_id', models.CharField(blank=True, max_length=200, verbose_name='ID cartella Drive output')),
                ('drive_oauth_account', models.EmailField(blank=True, max_length=254, verbose_name='account OAuth Drive')),
                ('creato_at', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'edizione',
                'verbose_name_plural': 'edizioni',
                'ordering': ['-anno'],
            },
        ),
        migrations.CreateModel(
            name='Dilazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuova_scadenza', models.DateField(verbose_name='nuova scadenza')),
                ('motivazione', models.TextField()),
                ('creata_at', models.DateTimeField(auto_now_add=True)),
                ('concessa_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dilazioni_concesse', to=settings.AUTH_USER_MODEL)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dilazioni', to='diaries.diario')),
            ],
            options={
                'verbose_name': 'dilazione',
                'verbose_name_plural': 'dilazioni',
                'ordering': ['-creata_at'],
            },
        ),
    ]
