# Generated by Django 6.0.5 on 2026-05-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oggetto', models.CharField(max_length=200)),
                ('corpo', models.TextField()),
                ('categoria', models.CharField(choices=[('tecnico', 'Problema tecnico'), ('compilazione', 'Difficoltà di compilazione'), ('accesso', 'Problema di accesso'), ('dilazione', 'Richiesta dilazione'), ('altro', 'Altro')], max_length=20)),
                ('stato', models.CharField(choices=[('aperto', 'Aperto'), ('in_lavorazione', 'In lavorazione'), ('chiuso', 'Chiuso')], db_index=True, default='aperto', max_length=20)),
                ('chiuso_at', models.DateTimeField(blank=True, null=True)),
                ('creato_at', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
                ('aperto_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_aperti', to=settings.AUTH_USER_MODEL)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assegnati', to=settings.AUTH_USER_MODEL)),
                ('diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='diaries.diario')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'ticket',
                'ordering': ['-creato_at'],
            },
        ),
        migrations.CreateModel(
            name='RispostaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('creata_at', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte_ticket', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risposte', to='helpdesk.ticket')),
            ],
            options={
                'verbose_name': 'risposta',
                'verbose_name_plural': 'risposte',
                'ordering': ['creata_at'],
            },
        ),
    ]
