# Generated by Django 6.0.5 on 2026-05-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esito', models.CharField(blank=True, choices=[('approvata', 'Approvata'), ('non_approvata', 'Non approvata'), ('maggiori_info', 'Maggiori informazioni richieste')], max_length=20, null=True)),
                ('stato', models.CharField(choices=[('assegnata', 'Assegnata'), ('in_revisione', 'In revisione (proposta PGV)'), ('confermata', 'Confermata')], default='assegnata', max_length=20)),
                ('proposta_esito', models.CharField(blank=True, choices=[('approvata', 'Approvata'), ('non_approvata', 'Non approvata'), ('maggiori_info', 'Maggiori informazioni richieste')], help_text='Esito proposto da un membro PGV (in attesa di conferma Incaricato).', max_length=20, null=True)),
                ('note', models.TextField(blank=True)),
                ('creata_at', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_at', models.DateTimeField(auto_now=True)),
                ('confermata_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valutazioni_confermate', to=settings.AUTH_USER_MODEL)),
                ('diario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valutazione', to='diaries.diario')),
                ('valutatore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valutazioni_espresse', to=settings.AUTH_USER_MODEL, verbose_name='valutatore')),
            ],
            options={
                'verbose_name': 'valutazione',
                'verbose_name_plural': 'valutazioni',
            },
        ),
        migrations.CreateModel(
            name='AssegnazionePGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creata_at', models.DateTimeField(auto_now_add=True)),
                ('assegnato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assegnazioni_fatte', to=settings.AUTH_USER_MODEL)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni_pgv', to='diaries.diario')),
                ('pgv', models.ForeignKey(limit_choices_to={'ruolo': 'pgv'}, on_delete=django.db.models.deletion.CASCADE, related_name='assegnazioni_ricevute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'assegnazione PGV',
                'verbose_name_plural': 'assegnazioni PGV',
                'unique_together': {('diario', 'pgv')},
            },
        ),
    ]
