# Generated by Django 6.0.5 on 2026-05-30 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparti', to='org.gruppo')),
            ],
        ),
        migrations.CreateModel(
            name='Squadriglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadriglie', to='org.reparto')),
            ],
        ),
        migrations.AddField(
            model_name='gruppo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gruppi', to='org.zona'),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_socio', models.CharField(help_text='Solo numerico, 4-8 cifre.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{4,8}$', 'Il codice socio deve essere numerico, da 4 a 8 cifre.')])),
                ('nome', models.CharField(max_length=120)),
                ('cognome', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('categoria', models.CharField(choices=[('capo', 'Capo'), ('ragazzo', 'Ragazzo')], max_length=10)),
                ('cellulare', models.CharField(blank=True, max_length=30)),
                ('branca', models.CharField(blank=True, max_length=40)),
                ('sesso', models.CharField(blank=True, max_length=1)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('livello_foca', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soci', to='org.gruppo')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soci', to='org.zona')),
            ],
            options={
                'indexes': [models.Index(fields=['cognome', 'nome'], name='org_socio_cognome_339d8c_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gruppo',
            unique_together={('nome', 'zona')},
        ),
    ]
