# Generated by Django 6.0.5 on 2026-06-04 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='provvisorio',
            field=models.BooleanField(default=False, help_text='True per i CRP generati automaticamente da import senza codice socio.'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='codice_socio',
            field=models.CharField(help_text='Numerico 4-8 cifre (ufficiale) oppure tmpNNNNN (provvisorio).', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{4,8}|tmp[0-9]{5})$', 'Il codice socio deve essere numerico (4-8 cifre) oppure provvisorio (tmpNNNNN).')]),
        ),
    ]
