# Generated by Django 6.0.5 on 2026-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_socio_provvisorio_alter_socio_codice_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='branca',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cellulare',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='socio',
            name='livello_foca',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='socio',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
