# Generated by Django 6.0.5 on 2026-05-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impostazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(default='Plancia', max_length=120)),
                ('sottotitolo', models.CharField(blank=True, default='Guidoncini Verdi - AGESCI Campania', max_length=200)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('email_mode', models.CharField(choices=[('reale', 'Invio reale (SMTP)'), ('simulato', 'Simulato (solo log su file)'), ('simulato_piu_invio', 'Simulato + invio reale')], default='simulato', max_length=20)),
                ('manutenzione', models.BooleanField(default=False)),
                ('debug_diagnostico', models.BooleanField(default=False)),
                ('debug_toolbar', models.BooleanField(default=False)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni',
                'verbose_name_plural': 'Impostazioni',
            },
        ),
    ]
