# Generated by Django 6.0.5 on 2026-06-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_footerlink_etichetta'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioni',
            name='email_provider',
            field=models.CharField(choices=[('smtp', 'SMTP tradizionale'), ('brevo', 'Brevo'), ('mailgun', 'Mailgun'), ('mailersend', 'MailerSend'), ('postmark', 'Postmark'), ('sendgrid', 'SendGrid'), ('sparkpost', 'SparkPost'), ('ses', 'Amazon SES')], default='smtp', help_text='SMTP tradizionale oppure provider transazionale (con tracking bounce/errori).', max_length=20, verbose_name='provider email'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='email_provider_api_key',
            field=models.CharField(blank=True, help_text='Chiave API del provider transazionale. Non usata con SMTP.', max_length=500, verbose_name='API key provider'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='email_provider_webhook_secret',
            field=models.CharField(blank=True, help_text='Secret per verificare i webhook di tracking (bounce, consegna, ecc.).', max_length=500, verbose_name='webhook secret'),
        ),
        migrations.AlterField(
            model_name='impostazioni',
            name='email_mode',
            field=models.CharField(choices=[('reale', 'Invio reale'), ('simulato', 'Simulato (solo log su file)'), ('simulato_piu_invio', 'Simulato + invio reale')], default='simulato', max_length=20),
        ),
        migrations.AlterField(
            model_name='impostazioni',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='mittente (from)'),
        ),
        migrations.AlterField(
            model_name='impostazioni',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP host'),
        ),
        migrations.AlterField(
            model_name='impostazioni',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP password'),
        ),
        migrations.AlterField(
            model_name='impostazioni',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP porta'),
        ),
        migrations.AlterField(
            model_name='impostazioni',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='SMTP usa TLS'),
        ),
        migrations.AlterField(
            model_name='impostazioni',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP utente'),
        ),
    ]
