# Generated by Django 6.0.5 on 2026-06-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_impostazioni_email_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impostazioni',
            name='email_mode',
            field=models.CharField(choices=[('reale', 'Invio reale'), ('simulato', 'Simulato (solo log su file)'), ('simulato_piu_invio', 'Simulato + invio reale'), ('mailpit', 'Mailpit (debug UI — /mailadmin/)')], default='simulato', max_length=20),
        ),
    ]
