# Generated by Django 6.0.5 on 2026-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0006_alter_impostazioni_email_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaStatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('privacy', 'Privacy Policy'), ('termini', 'Condizioni del Servizio')], max_length=20, unique=True)),
                ('titolo', models.CharField(max_length=200)),
                ('contenuto', models.TextField(blank=True)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pagina statica',
                'verbose_name_plural': 'Pagine statiche',
            },
        ),
    ]
