# Generated by Django 6.0.5 on 2026-06-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0007_pagina_statica'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailSMTPCredenziali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, unique=True, verbose_name='account Gmail')),
                ('access_token', models.CharField(blank=True, max_length=2000, verbose_name='access token')),
                ('refresh_token', models.CharField(max_length=2000, verbose_name='refresh token')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='scadenza token')),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credenziali Gmail SMTP',
                'verbose_name_plural': 'Credenziali Gmail SMTP',
            },
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='email_backend_massivo',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('transazionale', 'Provider transazionale')], default='transazionale', help_text='Backend per inviti bulk (Capi Reparto e Capi Squadriglia).', max_length=20, verbose_name='backend invii massivi'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='email_backend_standard',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('transazionale', 'Provider transazionale')], default='smtp', help_text='Backend per email di sistema (reset password, MFA, notifiche singole).', max_length=20, verbose_name='backend email standard'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='smtp_gmail_account',
            field=models.EmailField(blank=True, max_length=254, verbose_name='account Gmail OAuth collegato'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='smtp_use_gmail_oauth',
            field=models.BooleanField(default=False, help_text='Se attivo, usa XOAUTH2 per smtp.gmail.com invece di username/password.', verbose_name='usa Gmail OAuth2 per SMTP'),
        ),
    ]
