# Generated by Django 6.0.5 on 2026-06-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0008_email_dual_backend_gmail_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioni',
            name='mfa_obbligatoria_ruoli_estesi',
            field=models.BooleanField(default=True, help_text='Se disattivato, la MFA resta obbligatoria solo per gli Admin.', verbose_name='MFA obbligatoria per Segreteria e Incaricati EG'),
        ),
    ]
