# Generated by Django 6.0.5 on 2026-06-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0010_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioni',
            name='axes_cooloff_minutes',
            field=models.PositiveIntegerField(default=10, help_text="Dopo quanti minuti l'IP si sblocca automaticamente. 0 = blocco permanente.", verbose_name='minuti di blocco automatico'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='axes_failure_limit',
            field=models.PositiveIntegerField(default=5, help_text="Numero di tentativi di login errati prima che l'IP venga bloccato.", verbose_name='tentativi prima del blocco'),
        ),
    ]
