# Generated by Django 6.0.5 on 2026-06-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0011_axes_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioni',
            name='axes_use_attempt_expiration',
            field=models.BooleanField(default=True, help_text='Se attivo, i tentativi falliti scadono dopo il periodo di blocco e non vengono più conteggiati. Consigliato quando è impostato un blocco automatico.', verbose_name='scadenza tentativi (AXES_USE_ATTEMPT_EXPIRATION)'),
        ),
    ]
