# Generated by Django 6.0.5 on 2026-06-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0012_axes_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioni',
            name='allegati_max_px',
            field=models.PositiveIntegerField(default=1024, help_text='Lato maggiore in pixel delle immagini caricate come allegati. Le immagini più grandi vengono ridimensionate automaticamente al salvataggio.', verbose_name='dimensione massima immagini (px)'),
        ),
    ]
