# Generated by Django 6.0.5 on 2026-06-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0013_allegati_max_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioni',
            name='from_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome mittente'),
        ),
    ]
