# Generated by Django 6.0.5 on 2026-06-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0014_impostazioni_from_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='impostazioni',
            name='api_ratelimit_abilitato',
            field=models.BooleanField(default=True, help_text='Se attivo, limita il numero di chiamate API per utente/IP.', verbose_name='rate limiting API abilitato'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='api_ratelimit_per_minuto',
            field=models.PositiveIntegerField(default=60, help_text='Richieste API consentite per minuto per token/IP. 0 = illimitato.', verbose_name='max richieste al minuto (API)'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='api_ratelimit_per_ora',
            field=models.PositiveIntegerField(default=1000, help_text='Richieste API consentite per ora per token/IP. 0 = illimitato.', verbose_name="max richieste all'ora (API)"),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='app_funzioni_limitate',
            field=models.JSONField(blank=True, default=list, help_text='Lista di slug-funzione non disponibili nelle versioni deprecate. Es: ["pdf", "export_diari"].', verbose_name='funzioni limitate per versioni deprecate'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='app_messaggio_aggiornamento',
            field=models.TextField(blank=True, default='', help_text='Messaggio mostrato in-app quando è disponibile un aggiornamento.', verbose_name='messaggio aggiornamento app'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='app_versione_deprecata',
            field=models.CharField(blank=True, default='', help_text='Versioni inferiori a questa ricevono header X-App-Upgrade-Warning ma continuano a funzionare. Es: 2.1.0.', max_length=20, verbose_name='versione app deprecata (warning)'),
        ),
        migrations.AddField(
            model_name='impostazioni',
            name='app_versione_minima',
            field=models.CharField(blank=True, default='', help_text='Versioni app inferiori a questa ricevono 426 e non possono accedere. Es: 2.0.0. Vuoto = nessun blocco.', max_length=20, verbose_name='versione app minima'),
        ),
    ]
