# Generated by Django 6.0.5 on 2026-05-30 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogImportazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coca', 'Capi (Co.Ca.)'), ('ragazzi', 'Ragazzi'), ('evento', 'Anagrafiche diari (Evento)')], max_length=10)),
                ('file_nome', models.CharField(max_length=255)),
                ('creato_at', models.DateTimeField(auto_now_add=True)),
                ('totale', models.PositiveIntegerField(default=0)),
                ('ok', models.PositiveIntegerField(default=0)),
                ('scartati', models.PositiveIntegerField(default=0)),
                ('da_riconciliare', models.PositiveIntegerField(default=0)),
                ('creato_da', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_eseguiti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RigaImportazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('dati_grezzi', models.JSONField(default=dict)),
                ('stato_match', models.CharField(choices=[('ok', 'Associato'), ('da_riconciliare', 'Da riconciliare'), ('scartata', 'Scartata')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='imports.logimportazione')),
                ('socio_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.socio')),
            ],
        ),
    ]
