# Generated by Django 6.0.5 on 2026-06-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_edizione_evento_drive'),
        ('imports', '0001_initial'),
    ]

    operations = [
        # 1. Allarga prima la colonna, poi converte i dati, poi aggiorna le choices.
        migrations.AlterField(
            model_name='logimportazione',
            name='tipo',
            field=models.CharField(choices=[('coca', 'Capi (Co.Ca.)'), ('ragazzi', 'Ragazzi'), ('squadriglie', 'Squadriglie iscritte')], max_length=20),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("imports", "LogImportazione")
            .objects.filter(tipo="evento")
            .update(tipo="squadriglie"),
            reverse_code=lambda apps, schema_editor: apps.get_model("imports", "LogImportazione")
            .objects.filter(tipo="squadriglie")
            .update(tipo="evento"),
        ),
        migrations.AddField(
            model_name='logimportazione',
            name='edizione',
            field=models.ForeignKey(blank=True, help_text='Valorizzato solo per import squadriglie iscritte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_log', to='editions.edizione'),
        ),
    ]
