# Generated by Django 6.0.5 on 2026-05-30 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave', models.CharField(choices=[('invito_csq', 'invito_csq'), ('invito_crp', 'invito_crp'), ('invito_pgv', 'invito_pgv'), ('esito_pubblicato', 'esito_pubblicato'), ('dilazione', 'dilazione'), ('richiesta_info', 'richiesta_info')], max_length=40, unique=True)),
                ('oggetto', models.CharField(max_length=255)),
                ('corpo_html', models.TextField(help_text='HTML rich text. Usa i tag {{ ... }} disponibili.')),
                ('attivo', models.BooleanField(default=True)),
                ('aggiornato_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'template email',
                'verbose_name_plural': 'template email',
            },
        ),
        migrations.CreateModel(
            name='Invito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo_target', models.CharField(choices=[('admin', 'Admin'), ('segreteria', 'Segreteria regionale'), ('incaricato_eg', 'Incaricato EG (IABR EG)'), ('pgv', 'Membro Pattuglia Guidoncini Verdi'), ('crp', 'Capo Reparto'), ('csq', 'Capo Squadriglia')], max_length=20)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('stato', models.CharField(choices=[('inviato', 'Inviato'), ('attivato', 'Attivato'), ('scaduto', 'Scaduto')], default='inviato', max_length=10)),
                ('inviato_at', models.DateTimeField(auto_now_add=True)),
                ('attivato_at', models.DateTimeField(blank=True, null=True)),
                ('diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviti', to='diaries.diario')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviti_ricevuti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invito',
                'verbose_name_plural': 'inviti',
                'ordering': ['-inviato_at'],
            },
        ),
    ]
