# Generated by Django 6.0.5 on 2026-06-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invito',
            name='tipo',
            field=models.CharField(choices=[('standard', 'Standard (link email)'), ('codice_socio', 'Via codice socio (Capo Squadriglia)')], default='standard', max_length=15),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='chiave',
            field=models.CharField(choices=[('invito_csq', 'invito_csq'), ('invito_crp', 'invito_crp'), ('invito_pgv', 'invito_pgv'), ('invito_crp_csq_lista', 'invito_crp_csq_lista'), ('esito_pubblicato', 'esito_pubblicato'), ('dilazione', 'dilazione'), ('richiesta_info', 'richiesta_info'), ('password_reset', 'password_reset'), ('email_confirmation', 'email_confirmation')], max_length=40, unique=True),
        ),
    ]
