# Generated by Django 6.0.5 on 2026-06-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_invito_tipo_alter_mailtemplate_chiave'),
    ]

    operations = [
        migrations.AddField(
            model_name='invito',
            name='delivery_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='invito',
            name='delivery_status',
            field=models.CharField(choices=[('in_attesa', 'In attesa'), ('inviato', 'Inviato al provider'), ('consegnato', 'Consegnato'), ('bounce', 'Bounce (non recapitato)'), ('spam', 'Segnalato come spam'), ('fallito', 'Errore di invio')], default='in_attesa', max_length=20),
        ),
        migrations.AddField(
            model_name='invito',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
