# Generated by Django 6.0.5 on 2026-06-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_invito_delivery_error_invito_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='chiave',
            field=models.CharField(choices=[('invito_csq', 'invito_csq'), ('invito_crp', 'invito_crp'), ('invito_pgv', 'invito_pgv'), ('invito_crp_csq_lista', 'invito_crp_csq_lista'), ('esito_pubblicato', 'esito_pubblicato'), ('dilazione', 'dilazione'), ('richiesta_info', 'richiesta_info'), ('diario_pdf_in_generazione', 'diario_pdf_in_generazione'), ('diario_pdf_pronto', 'diario_pdf_pronto'), ('password_reset', 'password_reset'), ('email_confirmation', 'email_confirmation')], max_length=40, unique=True),
        ),
    ]
